#!/bin/bash
echo "# Facebook : fb.com/meowwyaww.cat.ph       #"
echo "# Github : github.com/JaysonSky/           #"
echo "# Termux : ( Pentesting Tools Installer )  #"
echo "# Type : python2 + (python script)         #"
