#!/bin/bash

apt-get update
apt-get install git
apt-get install python
apt-get install python2.3
apt-get upgrade
git clone https://github.com/JaysonSky/Pentesting-Tools.git
clear
echo "# Facebook : fb.com/meowwyaww.cat.ph       #"
echo "# Github : github.com/JaysonSky/           #"
echo "# Termux : ( Pentesting Tools Installer )  #"
echo "# Type : python2 + (python script)         #"
